### ISSUE TITLE
is this test ok?

### ISSUE THREAD

**Issue by oyosc** [fx-kirin/mt4-numpy-example#1]
hi,is this test ok?the version of python must be x86? my python version is windows x86-64;and through vs2010,i get the file of DLL,but in the mt4,it occurs cannot load PythonNumpyMean.dll
the dir of PythonNumpyMean.dll is MQL4/Libraries,so whether you know this? thanks

**Comment by fx-kirin** [comment]
Yeah, Python  must be the same as MT4's x86 instruction set, x86 because it is called from it.

**Comment by fx-kirin** [comment]
Just see the link in README.

http://fx-kirin.com/python/call-pythonnumpy-function-within-metatrader-4/

**Comment by oyosc** [comment]
oh,i think the file of DLL is wrong!
